export const preferences = [
    { value: "music", preference: "Music" },
    { value: "dance", preference: "Dance" },
    { value: "gaming", preference: "Gaming" },
    { value: "literary & dramatics", preference: "Literary And Dramatics" },
    { value: "lifeStyle", preference: "Life Style" },
    { value: "intracolleiate", preference: "Intra-College" },
    { value: "mis", preference: "Miscellaneous" },
    { value: "mestori", preference: "Mestori" },
    { value: "tfest", preference: "Technical Fest" },
    { value: "photography", preference: "Photography" },
    { value: "adeventure", preference: "Adventure" },
    { value: "akv", preference: "Acharya Kannada Vedike" },
    { value: "sports", preference: "Sports" },
    { value: "videoEditing", preference: "Video Editing" },
    { value: "defenceSquad", preference: "Defence Squad" },
    { value: "content", preference: "Content" },
    { value: "decoration", preference: "Decoration" },
    { value: "fine arts", preference: "Fine Arts" },
    { value: "design and digital art", preference: "Design and Digital Art" },
];